# action.yml
name: 'Swagger Codegen Action'
description: 'Run Swagger Codegen with Github Actions'
branding:
    icon: code
    color: green
runs:
  using: 'docker'
  image: 'docker://swaggerapi/swagger-codegen-cli-v3:3.0.46'
  args:
  - ${{ inputs.action }}
  - '-i'
  - ${{ inputs.input }}
  - '-l'
  - ${{ inputs.language }}
  - '-c'
  - ${{ inputs.config }}
  - '-t'
  - ${{ inputs.templates }}
inputs:
  language:
    description: Swagger language
    required: true
  input:
    description: Swagger file
    required: true
  action:
    description: swagger-codegen-cli action
    required: true
  config:
    description: swagger-codegen-cli -c
    required: true
  templates:
    description: swagger-codegen-cli -t
    required: true     
